### ISSUE TITLE
Add preview of event before submitting

### ISSUE THREAD

**Issue by brandonagr** [Dallas-Makerspace/calendar#103]
On the events/add page you enter lots of information and then click submit. It would be useful to have a preview of how the event will look on its events/view page before final submission. 

Either dynamically rendered on the submit event page as you enter details or as a second page that you click to with a View Preview button that is next to the Submit Event button, that View Preview page would need a way to navigate back while keeping all fields populated

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix
