### ISSUE TITLE
[Bug] Good SQL Sanitation, Bad Server side rendering, Ugly UX

### ISSUE THREAD

**Issue by denzuko** [Dallas-Makerspace/calendar#104]
* **Expected Results**
Given a class/event has been previously submitted
And User visits an event description
then event description should render without errors
* **Actual Results**
![](https://fb.pics/img/2019/06/28/Screen-Shot-2019-06-28-at-9.39.49-AM.md.png)
* **Additional Results**
N/A

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix
