### ISSUE TITLE
(bug) repeat users for a class may be inputed

### ISSUE THREAD

**Issue by denzuko** [Dallas-Makerspace/calendar#105]
* *Expected Results*
    Given one is not logged
    And one visits a class for the first time
    And one signs up with a similar email using the infinite google trick
    Then a new individual is added

    Given one is not logged
    And has previously registered for a class or one is the instructor
    And one signs up with a similar email using the infinite google trick
    Then a new individual is *not* added

* *Actual Results*
Given one is not logged
And one visits a class
And one signs up with a similar email using the infinite google trick
Then a new individual is added

**Comment by MikeColeGuru** [comment]
One can have emails for a non-gmail company formatted using the plus symbol and it not mean the same as gmail.   

For example:

A+Computer@notgmail.com
A+Plumbing@notgmail.com

**Comment by aceat64** [comment]
Google also ignores periods in the email address, so firstname.lastname@gmail.com is the same as firstnamelastname@gmail.com and first.name.last.name@gmail.com. I don't think this is a solvable issue without breaking for some users.

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix
