### ISSUE TITLE
DMS Feed shows as Vcard

### ISSUE THREAD

**Issue by denzuko** [Dallas-Makerspace/calendar#2]
* **Expected Results**:
   * When visiting https://calendar.dallasmakerspace.org/events/feed one should see a RSS feed
   * RSS Feed Content-Type should be `application/rss+xml`
   * When visiting https://calendar.dallasmakerspace.org/events/subscribe one should get a iCalendar file
   * iCalendar file should be a content type of 'text/calendar'

* **Actual Results**:
   * A VCALENDAR file is presented in text with ```Content-Type: text/html; charset=UTF-8```

**Comment by denzuko** [comment]
Hand in hand with "Easy way to add event to personal calendar or create a feed for Attending/hosting events (ics attachment to signup email)"

**Comment by MikeColeGuru** [comment]
I believe the feed was for mass import into Google Calendar when we were using that.  I don't think we are using it but I am not certain.

**Comment by MikeColeGuru** [comment]
I have extended it in the rss-feed branch to include /events/feed/rss, /events/feed/atom and /events/feed/json and the default is still the VCalendar mass

**Comment by MikeColeGuru** [comment]
I'm currently thinking about extending it to allow an RSS feed for each selection on the events page.  For example, if you select to only show a certain category, it will provide an RSS feed that corresponds.  
This would allow someone to get a feed for only the classes that they want to see.

What do you think?

**Comment by denzuko** [comment]
sounds very useful. I'd love to see the end result.

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix
