### ISSUE TITLE
Application Profiling and Optimization

### ISSUE THREAD

**Issue by denzuko** [Dallas-Makerspace/calendar#24]
* ** Actual Results**: 
   - Calendar is currently taking over 10sec to load the login page.

* ** Expected Results**:
   - Should take less than 1 second to retrieve and render a view

**Comment by denzuko** [comment]
Needs RCA and ssh access to the db, ldap, and app server.

**Comment by unholyknight** [comment]
This is an issue on the AD or server side and not within the app itself.

**Comment by denzuko** [comment]
has infrastructure resolved the AD server issues?
