### ISSUE TITLE
Blessing core Classes

### ISSUE THREAD

**Issue by denzuko** [Dallas-Makerspace/calendar#29]
Core classes allowed to bypass "Purgatory"

**Comment by MikeColeGuru** [comment]
I'm not certain what this enhancement is about.   Can you explain?

**Comment by denzuko** [comment]
This was created on behalf of either @diplomat or someone on talk, should be in a thread.

**Comment by brenly** [comment]
> John_Marlow
> Nov 5
> It appears that the calendar won’t let you schedule anything within a 48 hour window. I would like to see that window shortened - to either 12 or 24 hours.
> 
> It’s not obvious (to me, at least) what the logic for the 48 hour freeze might be.
>Would it be possible for any class that grants an AD group certification to pass through without delay? 
>
> Those are going to be the Required Ops & Safety classes and I can’t imagine an auditor disapproving those.
> 
> In my case, I was trying to schedule an Expansion meeting - not a class. Rooms were available. I wasn’t reserving a room for a private function. I wasn’t seeking an honorarium. But the calendar won’t let me schedule a room because it was within 48 hours. If the general case is that we need to allow 48 hours for an auditor to disapprove a non-honorarium event, then I understand it.

https://talk.dallasmakerspace.org/t/calendar-enhancements/44952

**Comment by denzuko** [comment]
Thanks @brenly.

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix
