### ISSUE TITLE
Fix minDate bug in DateTimePicker

### ISSUE THREAD

**Issue by clone1018** [Dallas-Makerspace/calendar#35]
It seems whenever setting minDate in DateTimePicker, it handles the hours / minutes incorrectly.

Reproduced bug: https://jsfiddle.net/fumspwte/

Workaround: https://jsfiddle.net/qja936cu/

**Comment by clone1018** [comment]
Fix should be in repeated in these 

https://github.com/Dallas-Makerspace/calendar/blob/2654c2f903358413141080e8513ece9deeecac18/webroot/js/app.js#L98-L161

**Comment by unholyknight** [comment]
Verifying this within the context of the application before patching.

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix
