### ISSUE TITLE
TravisCI discovered Errors in commit/9a80fc7d71c3ba7a9d6a51ad80fe2809e76b38da

### ISSUE THREAD

**Issue by denzuko** [Dallas-Makerspace/calendar#37]
* **Expected Results:**
  - Build passes
  - Version Tagged bumped up
  - Application is deployed to preprod in aws

* **Actual Results:**
  - Unit Tests fail
  - Several bugs discovered

* **Additional Details:** 
   - See [Build #7](https://travis-ci.org/Dallas-Makerspace/calendar/builds/278153546)

**Comment by denzuko** [comment]
We're up to [Build#78](https://travis-ci.org/Dallas-Makerspace/calendar/builds/378039782) and a few items have been addressed.

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix
