### ISSUE TITLE
(feat) Calendar sort option by newly added

### ISSUE THREAD

**Issue by denzuko** [Dallas-Makerspace/calendar#38]
As a user I would like to sort events by newly created so that I can see the latest events and classes added to the calendar.

Acceptable Criteria:
 
-  Should have a sort option or drop down to see newly added calendar events? 
- The table “events” has a field called “created” that would need to be referenced.

**Comment by clone1018** [comment]
Resolved in https://github.com/Dallas-Makerspace/calendar/pull/39

**Comment by denzuko** [comment]
Merged in PR #39
