### ISSUE TITLE
AI First support

### ISSUE THREAD

**Issue by denzuko** [Dallas-Makerspace/calendar#45]
As a user,
When I tell google assistant, "Ok, Google. What Events are at the Dallas Makerspace"
I am presented with old events from 2016.

Acceptance Criteria:
  - Should have calendar events indexed by google
  - "Ok Google, What Events are at the Dallas Makerspace" Should return current events for the week.
  - "Ok Google, What are today's classes are at the Dallas Makerspace" Should return current classes for today.
  - "Ok Google, What are today's events are at the Dallas Makerspace" Should return current events for today.

**Comment by denzuko** [comment]
looks like other than a few seo updates and intergration with the main WordPress site we could extend Google assistant ourselves. Already forked and updating a project for the extension part.

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix
