### ISSUE TITLE
Routing does not honor shorten domain

### ISSUE THREAD

**Issue by denzuko** [Dallas-Makerspace/calendar#46]
* **Expected Results**:
-  Able to login and use the site

* **Actual Results **:
- When attempting to login I'm redirected to http://calendar.dallas.ms/users/login?redirect=%2F and presented the message: 
```
Not Found

The requested URL /users/login was not found on this server.

Apache/2.4.7 (Ubuntu) Server at calendar.dallas.ms Port 80
```

**Comment by MikeColeGuru** [comment]
Yes, there are some routing issues that need to be addressed and some hard coded "calendar.dallasmakerspace.org" in the code as well.

**Comment by denzuko** [comment]
IMHO, that should be decoupled. Unless the application is directly reviewing access logs or doing some fancy thing with white label hosting then it shouldn't even need to bother with caring which host name its ran on (even then there's other ways than host name like an `x-...` header and a good load balancer).

**Comment by MikeColeGuru** [comment]
After thinking about this....
This has to do with Virtual Hosting.   
It uses the HTTP host header to determine what folder it should serve.
There can be many sites on one IP.
