### ISSUE TITLE
Docker Error

### ISSUE THREAD

**Issue by ATechAdventurer** [Dallas-Makerspace/calendar#51]
@denzuko 
When building the project into Docker, running:
` docker build https://github.com/Dallas-Makerspace/calendar.git` 
and 
` docker-compose up ` on the cloned repo both result in the following error: 
`ERROR: No build stage in current context`

**Comment by denzuko** [comment]
[Line 15 of docker-compose.yml](https://github.com/Dallas-Makerspace/calendar/blob/master/docker-compose.yml#L15) defines the build context as the same as `$PWD`. So one has to be in the same directory context as both the `docker-compose.yml` and `Dockerfile`. The `docker build <URL>` line you have there only builds the app container then the `docker-compose up` tries to start the services which also tries to build the image.

So, lets step it back to its most simplest procedure that is used in the CICD pipeline is:

  1) ` git clone https://github.com/Dallas-Makerspace/calendar.git dms_calendar`
  2) `cd $_ && docker-compose up --build --detach`

Which works out as step 1. does the clone to local while step 2. changes context into the local copy of the repo then does the image pull, build, and stands up the containers in one line.

**Comment by codes4coffee** [comment]
I think I figured out what the problem is. The MAINTAINER instruction is deprecated and will cause the Docker daemon to fail when building the image. I have a pull request with the fix. I've even tested it and it seems to work.
