### ISSUE TITLE
Super Admin

### ISSUE THREAD

**Issue by MikeColeGuru** [Dallas-Makerspace/calendar#54]
There needs to be a way for an admin to modify anything in the system without having to go to the database.  Calendar Admins should not have this power because there are many.  I propose creating a new Role/Group for Super Calendar Admins that have these rights.  It should be assigned for Infrastructure only.

**Comment by denzuko** [comment]
Sounds like a good idea. We may want this to be pulled off the ldap via one of our administrator groups. There may also be an audit log feature so individuals know who made changes, when and what those where with an ability to roll back but for the sake of scope lets keep it small.  Hows this:

```
As an member of @Dallas-Makerspace/infrastructure 
I need access to administrate all areas the callendar without needing to directly issue the sql to the  backend.
And I should be able to login with my current administrative groups to have access to all areas of the calendar
So that I can debug issues and resolve technical problems with the calendar and events.
```

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix
