### ISSUE TITLE
Can anything be done about cancellation reversal?

### ISSUE THREAD

**Issue by MikeColeGuru** [Dallas-Makerspace/calendar#55]
I've been guilty of this before.  I think I can't make it to a class so I cancel but then I find out that I can make it but my registration already fell off a cliff and I cannot register again.  I wonder what can be done to allow re-registration for an event?

Here is a recent victim

https://talk.dallasmakerspace.org/t/registration-issue/35917

**Comment by MikeColeGuru** [comment]
Update:  Bill Gee has answered to why this was implemented this way.  I still think there might be some way to delay it for a period of time.  

malcolmputer said "To my knowledge, you’re out of luck. It seems to be a problem with the calendar software."

bill said "It is time for this miserable misfeature to die a quick death. As I understand it, reregistering was deliberately prohibited to prevent making multiple charges for the same thing to a credit card, possibly setting fraud alerts.

Classes without a fee should allow registration despite prior cancellation."

**Comment by denzuko** [comment]
> Classes without a fee should allow registration despite prior cancellation."

100% agreed and it shouldn't be much of an issue to check where there is a fee on a class based on the [cost field](https://github.com/Dallas-Makerspace/calendar/blob/master/src/Model/Entity/Event.php#L19) of the event model.

**Comment by MikeColeGuru** [comment]
I have some information from David K and Steve B.

We should go ahead and allow resignups for all classes and events.
But we need to move the settling of the credit card until an end of day event.
This is so we can void transactions more often than refunding.

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix
