### ISSUE TITLE
Changing Event Dates/Times

### ISSUE THREAD

**Issue by MikeColeGuru** [Dallas-Makerspace/calendar#63]
Sometimes it is necessary to change the event times or dates.  It might be helpful if people that have signed up for it to be notified in some way that the event time has changed.

Example,

https://calendar.dallasmakerspace.org/events/view/6110
was changed to
https://calendar.dallasmakerspace.org/events/view/6146

**Comment by denzuko** [comment]
Considering nearly all of our members are on talk. Maybe we should have those notifications though talk's api?

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix
