### ISSUE TITLE
Add WaitList functionality to Calendar

### ISSUE THREAD

**Issue by zphelj** [Dallas-Makerspace/calendar#65]
When a class or event reaches capacity allow others to continue to sign up and be placed on a wait list.  Should someone who is confirmed for the event or class cancel, the first person on the waitlist moves up to confirmed status. When this occurs the person moving to confirmed status is notified via email and if opted in via SMS.  The wait list is FIFO.

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix
