### ISSUE TITLE
Calendar does not show custom error

### ISSUE THREAD

**Issue by MikeColeGuru** [Dallas-Makerspace/calendar#80]
When errors are generated during saves, it does not display the custom error.

For example, this has text in it but does not get displayed
$event->_subject->entity->[errors]["event_start"]["custom"]

**How to replicate**
Edit an event that is within 2 days of happening without changing the lead time config option.
The custom even warns you that you cannot edit the event within two days but it displays an error saying something is wrong with the fields.

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix
