### ISSUE TITLE
Include Rejection Message with Class Listing

### ISSUE THREAD

**Issue by Coding-Badly** [Dallas-Makerspace/calendar#81]
RE: https://talk.dallasmakerspace.org/t/equitable-class-rejection-criteria-specifically-related-to-description/47421/81

How difficult would it be to also include the rejection message with the class listing?

[Draco](https://talk.dallasmakerspace.org/t/equitable-class-rejection-criteria-specifically-related-to-description/47421/83)
I think it should be included along with a chat box with the admin and the ability for the event to be resubmitted.

[halachal](https://talk.dallasmakerspace.org/t/equitable-class-rejection-criteria-specifically-related-to-description/47421/84)
I think the simple solution is for an honorarium rejection to not equal a calendar rejection - the submitter can choose to withdraw their class or proceed as a non-honorarium event.

Look at this thread - if you force the auditors to go through something like this with each rejected submitter, they will probably burn out quite quickly. If they want to debate the merits, let them take it up with the board.

[Draco](https://talk.dallasmakerspace.org/t/equitable-class-rejection-criteria-specifically-related-to-description/47421/85)
They have to face resubmission anyway. This gives people a chance to explain themselves and correct the mistake without having to redo the entire submission. I do think they should also have the ability to change to non-honorarium but then it would have to go through the other process with the other set of admins.

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix
