### ISSUE TITLE
Add W9 link for bookkeeper

### ISSUE THREAD

**Issue by MikeColeGuru** [Dallas-Makerspace/calendar#86]
The bookkeeper should have a link to the current W9 on their report.

Currently, there is no way to choose a good W9 or for the system to know there is a correct one on file.
A way to select a file that has been uploaded as the correct W9.
This should also make note on the event creation screen that one is already accepted so they don't need to upload another.  Or Junk as many have done

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix
