### ISSUE TITLE
Calendar should warn about too large of upload

### ISSUE THREAD

**Issue by MikeColeGuru** [Dallas-Makerspace/calendar#89]
Currently, the system doesn't warn you that it will not display files larger than the max upload set in the php config.   It should warn you and stop submitting the event if the file is too large.

What it does, is allow it to go through but shows up in the database with an empty filename.

**Comment by MikeColeGuru** [comment]
![file-upload-bug](https://user-images.githubusercontent.com/19918682/49849050-85209d00-fd9d-11e8-8345-2058653f251b.png)

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix
