### ISSUE TITLE
Checkin API Endpoint

### ISSUE THREAD

**Issue by denzuko** [Dallas-Makerspace/calendar#9]
As a instructure
I would like to have members be able to badge in for attendance
So that I can claim credit for attendees at events

As a user
I would like be able to use my membership RFID badge to sign in for attendance to classes
So that I can enjoy the lesson and not have to use a pen and paper

Acceptance Criteria:
  - [ ] Should take RFID number as a parameter for an api endpoint to sign in
  - [ ] Should Return 200 OK when attendee is on the list
  - [ ] Should Return 401 Unauthorized when attendee is not on the list
  - [ ] Should Use RESTful methods
  - [ ] Should not break current code
  - [ ] Should not require authenticate

**Comment by denzuko** [comment]
Implementation of this will be moved to the android and PWA app.

Would need to create a controller to wrap around [EventsController::attending()](https://github.com/Dallas-Makerspace/calendar/blob/master/src/Controller/EventsController.php#L526) so an authenticated(jwt/saml) user can post that they attended.

For extra security methods would need to validate they are coming from the PWA/Android app via an x-client-token and modified user agent string.

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix
