### ISSUE TITLE
Uses same namespace for file uploads

### ISSUE THREAD

**Issue by MikeColeGuru** [Dallas-Makerspace/calendar#90]
Currently, when two or more event use the same filename for file uploads, they clash because they are stored in the same folder.  This should be fixed by moving each event into its own namespace. 

This may be fixed by switching to S3.  #87

**Comment by brenly** [comment]
Why not just set a sort of random file name with the correct file extension? at least until s3 can be rolled out. I can't imagine calendars needing more than one or two files uploaded. example "230423425239034954345.jpg"

**Comment by skyspook** [comment]
Fixed as part of v2.1.0
