### ISSUE TITLE
Double booking of the Lecture Hall

### ISSUE THREAD

**Issue by Coding-Badly** [Dallas-Makerspace/calendar#92]
RE: https://talk.dallasmakerspace.org/t/issue-january-10-double-booking-of-lecture-hall-12-14-18/47904

Highlights...

On Thursday Jan 10 an LED event is listed for the Lecture Hall from 6:30 to 7:30pm
On the same date a Win Shields is listed for the Lecture Hall from 7 to 10pm

https://calendar.dallasmakerspace.org/events/view/8146 5
https://calendar.dallasmakerspace.org/events/view/9075 4

**Comment by Coding-Badly** [comment]
A potential reason...
https://talk.dallasmakerspace.org/t/issue-january-10-double-booking-of-lecture-hall-12-14-18/47904/6

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix
