### ISSUE TITLE
Overlapping Events

### ISSUE THREAD

**Issue by MikeColeGuru** [Dallas-Makerspace/calendar#94]
There have been a number of overlapping events.

**To replicate bug:**
Create an event at a certain time room A
Create an event at overlapping times in room B
Edit an event and change rooms to the other room

You will have two events in the same room
This may also work with overlapping tools

**Error**
When this happens it complains in the debug log

```
2018-12-17 12:30:33 Notice: Notice (8): Undefined index: booking_start in [src/Model/Table/EventsTable.php, line 229]
Request URL: /events/edit/xxxx
...
2018-12-17 12:30:50 Notice: Notice (8): Undefined index: booking_end in [src/Model/Table/EventsTable.php, line 228]
Request URL: /events/edit/xxxx
```

**Comment by MikeColeGuru** [comment]
It looks like it only makes these available when they can be edited and normal users cannot edit event times, however they can change rooms.

https://github.com/Dallas-Makerspace/calendar/blob/578e5666dedc7ff88e1d91b412d1f5f0815cb9e7/src/Controller/EventsController.php#L1160

**Comment by MikeColeGuru** [comment]
@denzuko 

This looks like this might have fixed the issue ... 

https://github.com/Dallas-Makerspace/calendar/commit/591b28be5928b67324341754838339bf12470492

**Comment by limey-dms** [comment]
Updating/closing the old issues as stale/won't fix
